# Generated by Django 4.2.3 on 2024-03-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitid', models.CharField(max_length=20, unique=True, verbose_name='Organization unit')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('parentunit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.organizationunit', verbose_name='Parent Organization Unit')),
            ],
        ),
    ]
