# Generated by Django 4.2.3 on 2024-04-01 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplid', models.CharField(help_text='employee number', max_length=20, unique=True, verbose_name='employee')),
                ('name', models.CharField(help_text='employee name', max_length=60, verbose_name='name')),
                ('status', models.CharField(blank=True, choices=[('N', 'None'), ('M', 'Employed'), ('F', 'Resigned')], max_length=10, null=True)),
                ('employee_type', models.CharField(blank=True, max_length=20, null=True)),
                ('seniority_date', models.DateField(blank=True, null=True)),
                ('probation_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('N', 'None'), ('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='ID number')),
                ('marital_status', models.CharField(blank=True, choices=[('N', 'None'), ('M', 'Married'), ('S', 'Single'), ('W', 'Widowed'), ('D', 'Divorced')], max_length=10, null=True)),
                ('education', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='contact address')),
                ('emergency_contact', models.CharField(help_text='emergency contact', max_length=60, verbose_name='name')),
                ('Emergency_number', models.CharField(blank=True, max_length=40, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('orgnization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hrm.organizationunit')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hrm.persontitle')),
            ],
        ),
    ]
