# Generated by Django 4.2.3 on 2024-04-03 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_rename_telefax_companyinfo_telefax_and_more'),
        ('hrm', '0002_persontitle_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='countryregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.countryregion', verbose_name='Country/region'),
        ),
    ]
