# Generated by Django 4.2.3 on 2024-04-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_employee_countryregion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['emplid']},
        ),
    ]
