# Generated by Django 4.2.3 on 2024-04-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_alter_employee_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Emergency_number',
            new_name='emergency_number',
        ),
    ]
