# Generated by Django 4.2.3 on 2024-04-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_employee_created_by_employee_created_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='emergency contact', max_length=60, null=True, verbose_name='name'),
        ),
    ]
