# Generated by Django 4.2.3 on 2024-04-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_alter_employee_emergency_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
    ]
