# Generated by Django 4.2.3 on 2024-04-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_alter_employee_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persontitle',
            options={'verbose_name': 'person title'},
        ),
        migrations.AlterField(
            model_name='persontitle',
            name='name',
            field=models.CharField(help_text='person title', max_length=30, unique=True, verbose_name='name'),
        ),
    ]
