# Generated by Django 4.2.3 on 2023-11-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_language_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
    ]
