# Generated by Django 4.2.3 on 2023-12-04 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0015_group_description'),
        ('system', '0003_alter_language_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('menutype', models.CharField(blank=True, choices=[('N', 'Navbar'), ('S', 'Sidebar')], default='S', max_length=2, null=True)),
                ('seq', models.FloatField(blank=True, null=True, verbose_name='Order Number')),
                ('is_home', models.BooleanField(default=False, verbose_name='Home')),
                ('parentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.menu', verbose_name='Parent Id')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.permission')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='MenuLangName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.language')),
                ('menuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.menu')),
            ],
        ),
    ]
