# Generated by Django 4.2.3 on 2023-12-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_menu_menulangname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='parentid',
            new_name='parent',
        ),
    ]
