# Generated by Django 4.2.3 on 2023-12-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_menu_created_by_menu_created_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='seq',
            field=models.FloatField(blank=True, null=True, verbose_name='Order'),
        ),
    ]
