# Generated by Django 4.2.3 on 2024-01-03 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_menu_seq'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menulangname',
            unique_together={('menuid', 'lang')},
        ),
    ]
