# Generated by Django 5.0.4 on 2024-05-29 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0010_numbersequencetable_alter_unitconvert_markup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Tax code')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('roundoff', models.FloatField(default=0.01, help_text='Special rounding-off for VAT', verbose_name='Round-off')),
                ('roundoff_type', models.CharField(choices=[('O', 'round off'), ('U', 'up'), ('D', 'down')], default='O', max_length=2, verbose_name='Rounding form')),
                ('value', models.FloatField(help_text='Percentage or amount per unit')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.currency')),
            ],
            options={
                'verbose_name': 'VAT codes',
            },
        ),
        migrations.CreateModel(
            name='TaxItemGroupHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_item_group', models.CharField(max_length=10, unique=True, verbose_name='Item tax group')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('tax_code', models.ManyToManyField(to='ledger.taxtable')),
            ],
            options={
                'verbose_name': 'Item tax group',
            },
        ),
        migrations.CreateModel(
            name='TaxGroupHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_group', models.CharField(max_length=10, unique=True, verbose_name='Tax group')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('tax_code', models.ManyToManyField(to='ledger.taxtable')),
            ],
            options={
                'verbose_name': 'Tax group',
            },
        ),
    ]
