# Generated by Django 4.2.3 on 2024-03-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='currency')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Curreny',
        ),
    ]
