# Generated by Django 4.2.3 on 2024-03-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_currency_delete_curreny'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
