# Generated by Django 4.2.3 on 2024-03-12 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_currency_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='company name')),
                ('en_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='english name')),
                ('taxnum', models.CharField(blank=True, max_length=18, null=True, verbose_name='tax number')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='address')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='zip code')),
                ('telephone', models.CharField(blank=True, max_length=40, null=True)),
                ('telephoneext', models.CharField(blank=True, max_length=10, null=True, verbose_name='extension')),
                ('TeleFax', models.CharField(blank=True, max_length=40, null=True)),
                ('mobilephone', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('countryregion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.countryregion', verbose_name='country/region')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='name')),
                ('addresstype', models.CharField(blank=True, choices=[('N', 'none'), ('D', 'delivery'), ('I', 'invoice'), ('P', 'payment'), ('O', 'other')], default='N', max_length=2, null=True, verbose_name='address type')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.companyinfo')),
            ],
        ),
    ]
