# Generated by Django 4.2.3 on 2024-03-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_companyinfo_companyaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='mobilephone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='mobile phone'),
        ),
    ]
