# Generated by Django 4.2.3 on 2024-03-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_companyinfo_currency_companyinfo_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='web site'),
        ),
    ]
