# Generated by Django 4.2.3 on 2024-03-14 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_alter_companyinfo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='TeleFax',
            new_name='teleFax',
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='countryregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.countryregion', verbose_name='Country/region'),
        ),
        migrations.AlterField(
            model_name='countryregion',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='Country/region'),
        ),
    ]
