# Generated by Django 4.2.3 on 2024-04-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_menulangname_unique_together'),
        ('basic', '0008_rename_telefax_companyinfo_telefax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=5, unique=True, verbose_name='unit')),
                ('txt', models.CharField(blank=True, max_length=30, verbose_name='name')),
                ('unit_decimals', models.PositiveSmallIntegerField(default=2, verbose_name='decimals')),
                ('symbol', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'units',
            },
        ),
        migrations.AlterModelOptions(
            name='companyaddress',
            options={'verbose_name': 'person title'},
        ),
        migrations.CreateModel(
            name='UnitTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitid_txt', models.CharField(blank=True, max_length=10, verbose_name='text')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.language')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.unit')),
            ],
            options={
                'verbose_name': 'unit texts',
                'unique_together': {('unit', 'language')},
            },
        ),
        migrations.CreateModel(
            name='UnitConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=5, max_digits=9)),
                ('markup', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Additional quantity')),
                ('round_off', models.CharField(choices=[('O', 'round off'), ('U', 'up'), ('D', 'down')], default='O', max_length=2, verbose_name='round-off')),
                ('from_unit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='from_unit', to='basic.unit', verbose_name='from unit')),
                ('to_unit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='to_unit', to='basic.unit', verbose_name='to unit')),
            ],
            options={
                'verbose_name': 'unit conversion',
                'unique_together': {('from_unit', 'to_unit')},
            },
        ),
    ]
