# Generated by Django 4.2.3 on 2024-04-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_unit_alter_companyaddress_options_unittxt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequenceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_code', models.CharField(max_length=10, unique=True, verbose_name='number sequence code')),
                ('txt', models.CharField(blank=True, max_length=30, verbose_name='name')),
                ('lowest', models.PositiveIntegerField(default=1, verbose_name='smallest')),
                ('highest', models.PositiveIntegerField(verbose_name='largest')),
                ('next_rec', models.PositiveIntegerField(blank=True, verbose_name='next')),
                ('num_format', models.CharField(blank=True, max_length=30, verbose_name='format')),
            ],
            options={
                'verbose_name': 'number sequence',
            },
        ),
        migrations.AlterField(
            model_name='unitconvert',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='additional quantity'),
        ),
    ]
