# Generated by Django 5.0.4 on 2024-06-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_numbersequencetable_alter_unitconvert_markup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DlvDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Destination code')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Destination of delivery',
            },
        ),
        migrations.CreateModel(
            name='DlvMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Delivery Mode')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Mode of delivery',
            },
        ),
        migrations.CreateModel(
            name='DlvTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Delivery terms')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Terms of delivery',
            },
        ),
    ]
