from django.urls import path
from . import views


app_name = "invent"
urlpatterns = [
    path('setup/itemgroup/', views.ItemGroupListView.as_view(), name="itemgroup"),
    path('setup/itemgroup/create/', views.ItemGroupCreateView.as_view(), name="itemgroup-create"),
    path('setup/itemgroupjson/', views.ItemGroup_Json.as_view(), name="itemgroup-json"),
    path('setup/itemgroup/<int:pk>/update/', views.ItemGroupUpdateView.as_view(), name="itemgroup-update"),
    path('setup/itemgroup/<int:pk>/delete/', views.ItemGroupDeleteView.as_view(), name="itemgroup-delete"),
    path('setup/itemconfig/', views.ItemConfigListView.as_view(), name="itemconfig"),
    path('setup/itemconfig/create/', views.ItemConfigCreateView.as_view(), name="itemconfig-create"),
    path('setup/itemconfigjson/', views.ItemConfig_Json.as_view(), name="itemconfig-json"),
    path('setup/itemconfig/<int:pk>/update/', views.ItemConfigUpdateView.as_view(), name="itemconfig-update"),
    path('setup/itemconfig/<int:pk>/delete/', views.ItemConfigDeleteView.as_view(), name="itemconfig-delete"),
    path('setup/itemcolor/', views.ItemColorListView.as_view(), name="itemcolor"),
    path('setup/itemcolor/create/', views.ItemColorCreateView.as_view(), name="itemcolor-create"),
    path('setup/itemcolorjson/', views.ItemColor_Json.as_view(), name="itemcolor-json"),
    path('setup/itemcolor/<int:pk>/update/', views.ItemColorUpdateView.as_view(), name="itemcolor-update"),
    path('setup/itemcolor/<int:pk>/delete/', views.ItemColorDeleteView.as_view(), name="itemcolor-delete"),
    path('setup/itemsize/', views.ItemSizeListView.as_view(), name="itemsize"),
    path('setup/itemsize/create/', views.ItemSizeCreateView.as_view(), name="itemsize-create"),
    path('setup/itemsizejson/', views.ItemSize_Json.as_view(), name="itemsize-json"),
    path('setup/itemsize/<int:pk>/update/', views.ItemSizeUpdateView.as_view(), name="itemsize-update"),
    path('setup/itemsize/<int:pk>/delete/', views.ItemSizeDeleteView.as_view(), name="itemsize-delete"),
    path('setup/inventsite/', views.InventSiteListView.as_view(), name="inventsite"),
    path('setup/inventsite/create/', views.InventSiteCreateView.as_view(), name="inventsite-create"),
    path('setup/inventsitejson/', views.InventSite_Json.as_view(), name="inventsite-json"),
    path('setup/inventsite/<int:pk>/update/', views.InventSiteUpdateView.as_view(), name="inventsite-update"),
    path('setup/inventsite/<int:pk>/delete/', views.InventSiteDeleteView.as_view(), name="inventsite-delete"),
    path('setup/inventwarehouse/', views.InventWarehouseListView.as_view(), name="inventwarehouse"),
    path('setup/inventwarehouse/create/', views.InventWarehouseCreateView.as_view(), name="inventwarehouse-create"),
    path('setup/inventwarehousejson/', views.InventWarehouse_Json.as_view(), name="inventwarehouse-json"),
    path('setup/inventwarehouse/<int:pk>/update/', views.InventWarehouseUpdateView.as_view(), name="inventwarehouse-update"),
    path('setup/inventwarehouse/<int:pk>/delete/', views.InventWarehouseDeleteView.as_view(), name="inventwarehouse-delete"),
    path('setup/inventaisle/', views.InventAisleListView.as_view(), name="inventaisle"),
    path('setup/inventaisle/create/', views.InventAisleCreateView.as_view(), name="inventaisle-create"),
    path('setup/inventaislejson/', views.InventAisle_Json.as_view(), name="inventaisle-json"),
    path('setup/inventaisle/<int:pk>/update/', views.InventAisleUpdateView.as_view(), name="inventaisle-update"),
    path('setup/inventaisle/<int:pk>/delete/', views.InventAisleDeleteView.as_view(), name="inventaisle-delete"),
    path('setup/inventlocation/', views.InventLocationListView.as_view(), name="inventlocation"),
    path('setup/inventlocation/create/', views.InventLocationCreateView.as_view(), name="inventlocation-create"),
    path('setup/inventlocationjson/', views.InventLocation_Json.as_view(), name="inventlocation-json"),
    path('setup/inventlocation/<int:pk>/update/', views.InventLocationUpdateView.as_view(), name="inventlocation-update"),
    path('setup/inventlocation/<int:pk>/delete/', views.InventLocationDeleteView.as_view(), name="inventlocation-delete"),
    path('itemtable/', views.ItemTableListView.as_view(), name="itemtable"),
    path('itemtable/create/', views.ItemTableCreateView.as_view(), name="itemtable-create"),
    path('itemtablejson/', views.ItemTable_Json.as_view(), name="itemtable-json"),
    path('itemtable/<int:pk>/update/', views.ItemTableUpdateView.as_view(), name="itemtable-update"),
    path('itemtable/<int:pk>/delete/', views.ItemTableDeleteView.as_view(), name="itemtable-delete"),
    path('itemtable/<int:pk>/itemtxt/', views.manage_itemtxt, name="itemtable-txt"),
    path('inventbatch/', views.InventBatchListView.as_view(), name="inventbatch"),
    path('inventbatch/create/', views.InventBatchCreateView.as_view(), name="inventbatch-create"),
    path('inventbatchjson/', views.InventBatch_Json.as_view(), name="inventbatch-json"),
    path('inventbatch/<int:pk>/update/', views.InventBatchUpdateView.as_view(), name="inventbatch-update"),
    path('inventbatch/<int:pk>/delete/', views.InventBatchDeleteView.as_view(), name="inventbatch-delete"),
]