# Generated by Django 5.0.4 on 2024-06-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20, unique=True, verbose_name='Color')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Item color',
            },
        ),
        migrations.CreateModel(
            name='ItemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(max_length=20, unique=True, verbose_name='Config')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Item config',
            },
        ),
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, unique=True, verbose_name='Size')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Item size',
            },
        ),
    ]
