# Generated by Django 5.0.4 on 2024-06-06 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0002_itemcolor_itemconfig_itemsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=20, unique=True, verbose_name='Site')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Site',
            },
        ),
        migrations.CreateModel(
            name='InventWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=20, verbose_name='Warehouses')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invent.inventsite')),
            ],
            options={
                'verbose_name': 'Warehouses',
                'unique_together': {('warehouse', 'site')},
            },
        ),
        migrations.CreateModel(
            name='InventAisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ailse', models.CharField(max_length=20, verbose_name='Aisle')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invent.inventwarehouse')),
            ],
            options={
                'verbose_name': 'Aisle',
                'unique_together': {('warehouse', 'ailse')},
            },
        ),
        migrations.CreateModel(
            name='InventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20, verbose_name='Locations')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('ailse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invent.inventaisle')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invent.inventwarehouse')),
            ],
            options={
                'verbose_name': 'Locations',
                'unique_together': {('location', 'warehouse')},
            },
        ),
    ]
