# Generated by Django 5.0.4 on 2024-06-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0003_inventsite_inventwarehouse_inventaisle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventwarehouse',
            name='warehouse',
            field=models.CharField(max_length=20, unique=True, verbose_name='Warehouses'),
        ),
    ]
