# Generated by Django 5.0.4 on 2024-06-13 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_numbersequencetable_alter_unitconvert_markup'),
        ('invent', '0005_rename_ailse_inventaisle_aisle_and_more'),
        ('ledger', '0001_initial'),
        ('system', '0008_alter_menulangname_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=20, unique=True, verbose_name='Item number')),
                ('item_name', models.CharField(max_length=20, verbose_name='Item name')),
                ('item_type', models.CharField(choices=[('I', 'item'), ('S', 'service')], default='I', max_length=10, verbose_name='Item type')),
                ('item_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invent.itemgroup', verbose_name='Item group')),
            ],
            options={
                'verbose_name': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemTableModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('I', 'inventory'), ('P', 'purchase'), ('S', 'sales')], max_length=20, verbose_name='Module type')),
                ('overdelivery_pct', models.FloatField(verbose_name='Overdelivery')),
                ('underdelivery_pct', models.FloatField(verbose_name='Underdelivery')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.itemtable')),
                ('tax_item_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ledger.taxitemgroupheading')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='basic.unit')),
            ],
            options={
                'verbose_name': 'Inventory module parameters',
                'unique_together': {('item', 'module_type')},
            },
        ),
        migrations.CreateModel(
            name='ItemTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(blank=True, max_length=100, null=True, verbose_name='text')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.itemtable')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.language')),
            ],
            options={
                'verbose_name': 'item texts',
                'unique_together': {('item', 'language')},
            },
        ),
    ]
