# Generated by Django 5.0.4 on 2024-06-13 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0006_itemtable_itemtablemodule_itemtxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='standard_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invent.itemcolor', verbose_name='color'),
        ),
        migrations.AddField(
            model_name='itemtable',
            name='standard_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invent.itemconfig', verbose_name='config'),
        ),
        migrations.AddField(
            model_name='itemtable',
            name='standard_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invent.itemsize', verbose_name='size'),
        ),
    ]
