# Generated by Django 5.0.4 on 2024-06-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0007_itemtable_standard_color_itemtable_standard_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtable',
            name='item_name',
            field=models.CharField(max_length=60, verbose_name='Item name'),
        ),
        migrations.AlterField(
            model_name='itemtablemodule',
            name='overdelivery_pct',
            field=models.FloatField(default=0, help_text='Accepted overdelivery in percentage', verbose_name='Overdelivery'),
        ),
        migrations.AlterField(
            model_name='itemtablemodule',
            name='underdelivery_pct',
            field=models.FloatField(default=0, help_text='Accepted underdelivery in percentage', verbose_name='Underdelivery'),
        ),
        migrations.CreateModel(
            name='InventBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=20, verbose_name='Batch number')),
                ('exp_date', models.DateField(verbose_name='Expiry date')),
                ('prod_date', models.DateField(verbose_name='Manufacturing date')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.itemtable')),
            ],
            options={
                'verbose_name': 'Batches',
                'unique_together': {('item', 'batch_id')},
            },
        ),
        migrations.CreateModel(
            name='InventDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invent.inventbatch')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invent.itemcolor', verbose_name='color')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invent.itemconfig', verbose_name='config')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invent.inventlocation')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invent.inventsite')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invent.itemsize', verbose_name='size')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='invent.inventwarehouse')),
            ],
            options={
                'verbose_name': 'Inventory dimensions',
                'unique_together': {('batch', 'site', 'warehouse', 'location', 'config', 'size', 'color')},
            },
        ),
        migrations.CreateModel(
            name='InventSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_qty', models.DecimalField(decimal_places=2, help_text='Financially entered quantity', max_digits=9, verbose_name='Posted quantity')),
                ('post_value', models.DecimalField(decimal_places=2, help_text='Inventory value for the financially updated quantity.', max_digits=9, verbose_name='Financial cost amount')),
                ('deducted', models.DecimalField(decimal_places=2, help_text='Quantity that has been physically deducted, but not posted.', max_digits=9, verbose_name='Deducted')),
                ('received', models.DecimalField(decimal_places=2, help_text='Physical quantity received, but not posted', max_digits=9, verbose_name='Received')),
                ('reserv_physical', models.DecimalField(decimal_places=2, help_text='Quantity reserved of the physical quantity', max_digits=9, verbose_name='Physical reserved')),
                ('reserv_ordered', models.DecimalField(decimal_places=2, help_text='Quantity reserved on quantity ordered', max_digits=9, verbose_name='Ordered reserved')),
                ('onorder', models.DecimalField(decimal_places=2, help_text='Quantity on order', max_digits=9, verbose_name='On order')),
                ('ordered', models.DecimalField(decimal_places=2, help_text='Quantity ordered', max_digits=9, verbose_name='Ordered')),
                ('closed', models.BooleanField(help_text='Is the on-hand inventory closed, that is with no quantity and value?', verbose_name='Closed')),
                ('inventdim', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invent.inventdim')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='invent.itemtable')),
            ],
            options={
                'verbose_name': 'On-hand inventory',
                'unique_together': {('item', 'inventdim')},
            },
        ),
    ]
