# Generated by Django 5.0.4 on 2024-06-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Vendor group')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Vendor groups',
            },
        ),
    ]
