# Generated by Django 5.0.4 on 2024-07-09 07:03

import django.db.models.deletion
import utils.common_field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_dlvdestination_dlvmode_dlvterm'),
        ('hrm', '0009_alter_persontitle_options_alter_persontitle_name'),
        ('ledger', '0003_alter_paymterm_code'),
        ('system', '0008_alter_menulangname_unique_together'),
        ('vend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.CharField(max_length=20, unique=True, verbose_name='Account')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Short name')),
                ('url', models.URLField(blank=True, null=True, verbose_name='web site')),
                ('incl_tax', models.BooleanField(help_text='Do prices include sales tax?', verbose_name='Prices incl. sales tax')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('Blocked', models.BooleanField(help_text='Is the account locked?', verbose_name='Stopped')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_dt', models.DateTimeField(auto_now=True)),
                ('countryregion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.countryregion', verbose_name='Country/region')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creater', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.currency')),
                ('dlv_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.dlvdestination', verbose_name='Destination of delivery')),
                ('dlv_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.dlvmode', verbose_name='Mode of delivery')),
                ('dlv_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.dlvterm', verbose_name='Terms of delivery')),
                ('invoice_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vend.vendtable', verbose_name='Invoice account')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.language')),
                ('main_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee', verbose_name='Main contact')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifieder', to=settings.AUTH_USER_MODEL)),
                ('paym_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.paymterm', verbose_name='Terms of payment')),
                ('tax_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ledger.taxgroupheading')),
                ('vend_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vend.vendgroup', verbose_name='Country/region')),
            ],
            options={
                'verbose_name': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='VendContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(verbose_name='Primary')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Contact')),
                ('telephone', models.CharField(blank=True, max_length=40, null=True)),
                ('telephoneext', models.CharField(blank=True, max_length=10, null=True, verbose_name='extension')),
                ('teleFax', models.CharField(blank=True, max_length=40, null=True)),
                ('mobilephone', models.CharField(blank=True, max_length=40, null=True, verbose_name='mobile phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vendtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vend.vendtable', verbose_name='Vend account')),
            ],
            options={
                'verbose_name': 'Vendor contact',
            },
        ),
        migrations.CreateModel(
            name='VendAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('is_primary', models.BooleanField(verbose_name='Primary')),
                ('addresstype', utils.common_field.AddressType(choices=[('N', 'none'), ('D', 'delivery'), ('I', 'invoice'), ('P', 'payment'), ('O', 'other')], default='N', max_length=2, verbose_name='address type')),
                ('address', models.TextField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip code')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('State', models.CharField(blank=True, max_length=30, null=True, verbose_name='State')),
                ('countryregion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.countryregion', verbose_name='Country/region')),
                ('vendtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vend.vendtable', verbose_name='Vend account')),
            ],
            options={
                'verbose_name': 'Vendor addresses',
            },
        ),
    ]
