# Generated by Django 5.0.4 on 2024-07-10 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0002_vendtable_vendcontact_vendaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendtable',
            name='Blocked',
        ),
        migrations.AlterField(
            model_name='vendtable',
            name='incl_tax',
            field=models.BooleanField(default=True, help_text='Do prices include sales tax?', verbose_name='Prices incl. sales tax'),
        ),
        migrations.AlterField(
            model_name='vendtable',
            name='vend_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='vend.vendgroup'),
        ),
        migrations.AddField(
            model_name='vendtable',
            name='blocked',
            field=models.BooleanField(default=False, help_text='Is the account locked?', verbose_name='Stopped'),
        ),
    ]
