# Generated by Django 5.0.4 on 2024-07-17 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0003_remove_vendtable_blocked_alter_vendtable_incl_tax_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendaddress',
            name='is_primary',
            field=models.BooleanField(help_text='Primary address for address book record.', verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='vendtable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creater', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='vendtable',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date time'),
        ),
        migrations.AlterField(
            model_name='vendtable',
            name='lastmodified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified date time'),
        ),
        migrations.AlterField(
            model_name='vendtable',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifieder', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='vendtable',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Internet address'),
        ),
        migrations.AlterUniqueTogether(
            name='vendaddress',
            unique_together={('vendtable', 'name')},
        ),
    ]
