# Generated by Django 5.0.4 on 2024-07-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0004_alter_vendaddress_is_primary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendaddress',
            old_name='State',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='vendaddress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='vendcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='vendcontact',
            name='mobilephone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Mobile phone'),
        ),
        migrations.AlterField(
            model_name='vendcontact',
            name='teleFax',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='vendcontact',
            name='telephoneext',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Extension'),
        ),
    ]
