# Generated by Django 4.2.3 on 2023-10-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_group_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='desc',
        ),
    ]
