# Generated by Django 4.2.3 on 2023-10-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_group_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
