# Generated by Django 4.2.3 on 2023-11-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_password', 'Set user password'), ('change_password', 'Change user password')]},
        ),
    ]
