# Generated by Django 4.2.3 on 2023-11-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('set_profile', 'Set user profile'),)},
        ),
    ]
