# Generated by Django 4.2.3 on 2024-04-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_alter_employee_notes'),
        ('authentication', '0007_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hrm.employee'),
        ),
    ]
